name: langchain-snowpoc
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - pip
  - pip:
    - pyarrow=15.0.2
    - snowflake-connector-python=3.7.1
    - snowflake-snowpark-python=1.13.0
    - snowflake-ml-python=1.3.0
    - langchain=0.1.12
    - langchain-core=0.1.32
    - jupyterlab=4.1.5
    - beautifulsoup4=4.12.3
    - streamlit=1.32.2
    - -r requirements.txt
